[package]
name = "min-max-throughput"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.3.5"
rand = "0.8.4"

[profile.release]
lto = "thin"

[profile.bench]
lto = "thin"

[[bench]]
name = "min_max"
harness = false
